export const verses = [
  { day: 1, verse: 'El Señor es mi pastor, nada me falta.', reference: 'Salmo 23,1' },
  { day: 2, verse: 'Porque yo sé muy bien los planes que tengo para vosotros, planes de paz y no de aflicción.', reference: 'Jeremías 29,11' },
  { day: 3, verse: 'Todo tiene su momento, y cada cosa su tiempo bajo el cielo.', reference: 'Eclesiastés 3,1' },
  { day: 4, verse: 'Mira que voy a hacer algo nuevo, ya está brotando, ¿no lo notas?', reference: 'Isaías 43,19' },
  { day: 5, verse: 'El Señor es mi luz y mi salvación, ¿a quién temeré?', reference: 'Salmo 27,1' },
  { day: 6, verse: 'Dios es nuestro refugio y nuestra fuerza, auxilio siempre a punto en la angustia.', reference: 'Salmo 46,2' },
  { day: 7, verse: 'Aunque pase por el valle de tinieblas, no temo ningún mal, porque Tú estás conmigo.', reference: 'Salmo 23,4' },
  { day: 8, verse: 'Pero los que esperan en el Señor renuevan sus fuerzas, vuelan como las águilas.', reference: 'Isaías 40,31' },
  { day: 9, verse: 'El Señor te bendiga y te guarde.', reference: 'Números 6,24' },
  { day: 10, verse: 'Alégrense siempre en el Señor; se lo repito, alégrense.', reference: 'Filipenses 4,4' },
  { day: 11, verse: 'Tu bondad y tu misericordia me acompañan todos los días de mi vida.', reference: 'Salmo 23,6' },
  { day: 12, verse: 'El Señor es bueno con todos, es cariñoso con todas sus criaturas.', reference: 'Salmo 145,9' },
  { day: 13, verse: 'Confía en el Señor de todo corazón, no te apoyes en tu propia inteligencia.', reference: 'Proverbios 3,5' },
  { day: 14, verse: 'El Señor está cerca de los que tienen el corazón quebrantado.', reference: 'Salmo 34,19' },
  { day: 15, verse: 'Dichosos los que lloran, porque serán consolados.', reference: 'Mateo 5,4' },
  { day: 16, verse: 'Dichosos los misericordiosos, porque ellos alcanzarán misericordia.', reference: 'Mateo 5,7' },
  { day: 17, verse: 'Dichosos los que trabajan por la paz, porque serán llamados hijos de Dios.', reference: 'Mateo 5,9' },
  { day: 18, verse: 'Vosotros sois la luz del mundo. No puede ocultarse una ciudad puesta en lo alto de un monte.', reference: 'Mateo 5,14' },
  { day: 19, verse: 'Brille así vuestra luz ante los hombres, para que vean vuestras buenas obras.', reference: 'Mateo 5,16' },
  { day: 20, verse: 'No tengáis miedo; vosotros valéis más que muchos pájaros.', reference: 'Mateo 10,31' },
  { day: 21, verse: 'Venid a mí todos los que estáis fatigados y agobiados, y yo os aliviaré.', reference: 'Mateo 11,28' },
  { day: 22, verse: 'Porque donde dos o tres están reunidos en mi nombre, allí estoy yo en medio de ellos.', reference: 'Mateo 18,20' },
  { day: 23, verse: 'Para Dios todo es posible.', reference: 'Mateo 19,26' },
  { day: 24, verse: 'Amarás al Señor tu Dios con todo tu corazón, con toda tu alma y con toda tu mente.', reference: 'Mateo 22,37' },
  { day: 25, verse: 'Amarás a tu prójimo como a ti mismo.', reference: 'Mateo 22,39' },
  { day: 26, verse: 'Yo estaré con vosotros todos los días hasta el fin del mundo.', reference: 'Mateo 28,20' },
  { day: 27, verse: 'Conviértanse y crean en la Buena Noticia.', reference: 'Marcos 1,15' },
  { day: 28, verse: 'Todo es posible para el que cree.', reference: 'Marcos 9,23' },
  { day: 29, verse: 'Ama al Señor tu Dios con todo tu corazón, con toda tu alma, con toda tu mente y con todas tus fuerzas.', reference: 'Marcos 12,30' },
  { day: 30, verse: 'No temas, cree solamente.', reference: 'Marcos 5,36' },
  { day: 31, verse: 'El que no ama no ha conocido a Dios, porque Dios es amor.', reference: '1 Juan 4,8' },
  { day: 32, verse: 'En esto consiste el amor: no en que nosotros hayamos amado a Dios, sino en que Él nos amó primero.', reference: '1 Juan 4,10' },
  { day: 33, verse: 'Dios es amor, y el que permanece en el amor permanece en Dios y Dios en él.', reference: '1 Juan 4,16' },
  { day: 34, verse: 'Sobre todo, revístanse del amor, que es el vínculo de la perfecta unión.', reference: 'Colosenses 3,14' },
  { day: 35, verse: 'Porque tanto amó Dios al mundo que dio a su Hijo único.', reference: 'Juan 3,16' },
  { day: 36, verse: 'Nadie tiene amor más grande que el que da la vida por sus amigos.', reference: 'Juan 15,13' },
  { day: 37, verse: 'Sean uno. Como Tú, Padre, estás en mí y yo en ti, que también ellos sean uno en nosotros.', reference: 'Juan 17,21' },
  { day: 38, verse: 'El amor echa fuera el temor.', reference: '1 Juan 4,18' },
  { day: 39, verse: 'Tengamos amor, no de palabra ni de lengua, sino de verdad y de obras.', reference: '1 Juan 3,18' },
  { day: 40, verse: 'Sobre todo, mantengan entre ustedes un amor intenso, porque el amor cubre multitud de pecados.', reference: '1 Pedro 4,8' },
  { day: 41, verse: 'Que el Señor os haga crecer y abundar en amor unos para con otros.', reference: '1 Tesalonicenses 3,12' },
  { day: 42, verse: 'Sed buenos y compasivos unos con otros, perdonándoos mutuamente.', reference: 'Efesios 4,32' },
  { day: 43, verse: 'Someteos unos a otros en el temor de Cristo.', reference: 'Efesios 5,21' },
  { day: 44, verse: 'Nada hagáis por rivalidad ni por vanagloria, sino con humildad.', reference: 'Filipenses 2,3' },
  { day: 45, verse: 'Tened entre vosotros los mismos sentimientos que Cristo Jesús.', reference: 'Filipenses 2,5' },
  { day: 46, verse: 'La paz de Dios, que supera todo conocimiento, guardará vuestros corazones.', reference: 'Filipenses 4,7' },
  { day: 47, verse: 'Todo lo puedo en Aquel que me fortalece.', reference: 'Filipenses 4,13' },
  { day: 48, verse: 'Que la palabra de Cristo habite en vosotros en toda su riqueza.', reference: 'Colosenses 3,16' },
  { day: 49, verse: 'Dad gracias en toda ocasión.', reference: '1 Tesalonicenses 5,18' },
  { day: 50, verse: 'No apaguéis el Espíritu.', reference: '1 Tesalonicenses 5,19' },
  { day: 51, verse: 'Dios no nos ha dado un espíritu de timidez, sino de fortaleza, amor y prudencia.', reference: '2 Timoteo 1,7' },
  { day: 52, verse: 'Toda la Escritura es inspirada por Dios y útil para enseñar, reprender, corregir y educar en la justicia.', reference: '2 Timoteo 3,16' },
  { day: 53, verse: 'El amor no pasa nunca.', reference: '1 Corintios 13,8' },
  { day: 54, verse: 'El amor es paciente, es amable; no tiene envidia, no es jactancioso, no se engríe.', reference: '1 Corintios 13,4' },
  { day: 55, verse: 'La fe es garantía de lo que se espera, la prueba de las realidades que no se ven.', reference: 'Hebreos 11,1' },
  { day: 56, verse: 'Sin fe es imposible agradar a Dios.', reference: 'Hebreos 11,6' },
  { day: 57, verse: 'Jesucristo es el mismo ayer, hoy y siempre.', reference: 'Hebreos 13,8' },
  { day: 58, verse: 'Pedid y se os dará; buscad y hallaréis; llamad y se os abrirá.', reference: 'Mateo 7,7' },
  { day: 59, verse: 'El que persevere hasta el fin se salvará.', reference: 'Mateo 10,22' },
  { day: 60, verse: 'Si tuvierais fe como un grano de mostaza, diríais a esa montaña: ’trasládate’ y se trasladaría.', reference: 'Mateo 17,20' },
  { day: 61, verse: 'Bienaventurados los que no han visto y han creído.', reference: 'Juan 20,29' },
  { day: 62, verse: 'No se turbe vuestro corazón. Creéis en Dios, creed también en mí.', reference: 'Juan 14,1' },
  { day: 63, verse: 'Yo soy el Camino, la Verdad y la Vida.', reference: 'Juan 14,6' },
  { day: 64, verse: 'El que cree en mí, aunque muera, vivirá.', reference: 'Juan 11,25' },
  { day: 65, verse: 'Yo he venido para que tengan vida, y la tengan en abundancia.', reference: 'Juan 10,10' },
  { day: 66, verse: 'Yo soy el pan de vida. El que viene a mí no tendrá hambre.', reference: 'Juan 6,35' },
  { day: 67, verse: 'Conoceréis la verdad, y la verdad os hará libres.', reference: 'Juan 8,32' },
  { day: 68, verse: 'Yo soy la luz del mundo; el que me siga no caminará en tinieblas.', reference: 'Juan 8,12' },
  { day: 69, verse: 'Si Dios está por nosotros, ¿quién estará contra nosotros?', reference: 'Romanos 8,31' },
  { day: 70, verse: 'El justo vivirá por la fe.', reference: 'Romanos 1,17' },
  { day: 71, verse: 'Donde abundó el pecado, sobreabundó la gracia.', reference: 'Romanos 5,20' },
  { day: 72, verse: 'Todo contribuye al bien de los que aman a Dios.', reference: 'Romanos 8,28' },
  { day: 73, verse: 'Dios es fiel y no permitirá que seáis tentados más allá de vuestras fuerzas.', reference: '1 Corintios 10,13' },
  { day: 74, verse: 'El que comenzó en vosotros la buena obra la irá perfeccionando hasta el día de Cristo Jesús.', reference: 'Filipenses 1,6' },
  { day: 75, verse: 'Por gracia habéis sido salvados mediante la fe; esto no viene de vosotros, es don de Dios.', reference: 'Efesios 2,8' },
  { day: 76, verse: 'Si alguno está en Cristo, es una nueva creación; lo viejo pasó, ha llegado lo nuevo.', reference: '2 Corintios 5,17' },
  { day: 77, verse: 'El que no naciere de nuevo no puede ver el reino de Dios.', reference: 'Juan 3,3' },
  { day: 78, verse: 'Si hemos muerto con Cristo, creemos que también viviremos con Él.', reference: 'Romanos 6,8' },
  { day: 79, verse: 'Donde está el Espíritu del Señor, allí hay libertad.', reference: '2 Corintios 3,17' },
  { day: 80, verse: 'Revestíos del hombre nuevo, creado según Dios en justicia y santidad verdadera.', reference: 'Efesios 4,24' },
  { day: 81, verse: 'Caminad en el amor como Cristo os amó.', reference: 'Efesios 5,2' },
  { day: 82, verse: 'Despojaos del hombre viejo y vestíos del nuevo.', reference: 'Colosenses 3,9-10' },
  { day: 83, verse: 'Procurad ante todo su Reino y su justicia, y todo lo demás se os dará por añadidura.', reference: 'Mateo 6,33' },
  { day: 84, verse: 'No juzguéis, para que no seáis juzgados.', reference: 'Mateo 7,1' },
  { day: 85, verse: 'Tratad a los demás como queréis que ellos os traten.', reference: 'Mateo 7,12' },
  { day: 86, verse: 'No solo de pan vive el hombre, sino de toda palabra que sale de la boca de Dios.', reference: 'Mateo 4,4' },
  { day: 87, verse: 'El que quiera salvar su vida la perderá; pero el que pierda su vida por mí y por el Evangelio la salvará.', reference: 'Marcos 8,35' },
  { day: 88, verse: 'El Hijo del hombre no vino a ser servido, sino a servir y dar su vida en rescate por muchos.', reference: 'Marcos 10,45' },
  { day: 89, verse: 'Bienaventurados los pobres de espíritu, porque de ellos es el Reino de los Cielos.', reference: 'Mateo 5,3' },
  { day: 90, verse: 'Bienaventurados los limpios de corazón, porque ellos verán a Dios.', reference: 'Mateo 5,8' },
  { day: 91, verse: 'Vosotros sois la sal de la tierra.', reference: 'Mateo 5,13' },
  { day: 92, verse: 'Cargad con mi yugo y aprended de mí, que soy manso y humilde de corazón.', reference: 'Mateo 11,29' },
  { day: 93, verse: 'Mi yugo es suave y mi carga ligera.', reference: 'Mateo 11,30' },
  { day: 94, verse: 'El Reino de los Cielos se parece a un tesoro escondido en el campo.', reference: 'Mateo 13,44' },
  { day: 95, verse: 'El Reino de los Cielos se parece a un mercader que busca perlas finas.', reference: 'Mateo 13,45' },
  { day: 96, verse: 'La sabiduría de lo alto es, ante todo, pura, luego pacífica, comprensiva, dócil, llena de misericordia.', reference: 'Santiago 3,17' },
  { day: 97, verse: 'Así también la fe, si no tiene obras, está completamente muerta.', reference: 'Santiago 2,17' },
  { day: 98, verse: 'Sed hacedores de la Palabra y no solo oyentes.', reference: 'Santiago 1,22' },
  { day: 99, verse: 'La religión pura e intachable ante Dios Padre es esta: visitar a los huérfanos y a las viudas.', reference: 'Santiago 1,27' },
  { day: 100, verse: 'Confesaos mutuamente vuestros pecados y orad unos por otros para que seáis curados.', reference: 'Santiago 5,16' },
  { day: 101, verse: 'Sobrellevad los unos las cargas de los otros, y así cumpliréis la ley de Cristo.', reference: 'Gálatas 6,2' },
  { day: 102, verse: 'Porque todos sois hijos de Dios por la fe en Cristo Jesús.', reference: 'Gálatas 3,26' },
  { day: 103, verse: 'Ya no hay judío ni griego, esclavo ni libre, hombre ni mujer, porque todos sois uno en Cristo Jesús.', reference: 'Gálatas 3,28' },
  { day: 104, verse: 'El fruto del Espíritu es: amor, alegría, paz, paciencia, afabilidad, bondad, fidelidad.', reference: 'Gálatas 5,22' },
  { day: 105, verse: 'Cristo nos liberó para la libertad.', reference: 'Gálatas 5,1' },
  { day: 106, verse: 'Un solo cuerpo y un solo Espíritu, como una es la esperanza a la que habéis sido llamados.', reference: 'Efesios 4,4' },
  { day: 107, verse: 'Un Señor, una fe, un bautismo, un Dios y Padre de todos.', reference: 'Efesios 4,5-6' },
  { day: 108, verse: 'La comunidad de los creyentes tenía un solo corazón y una sola alma.', reference: 'Hechos 4,32' },
  { day: 109, verse: 'Todos ellos perseveraban unánimes en la oración.', reference: 'Hechos 1,14' },
  { day: 110, verse: 'Acudían asiduamente a la enseñanza de los apóstoles, a la comunión, a la fracción del pan y a las oraciones.', reference: 'Hechos 2,42' },
  { day: 111, verse: 'El Señor agregaba cada día a la comunidad a los que se iban salvando.', reference: 'Hechos 2,47' },
  { day: 112, verse: 'No podemos dejar de hablar de lo que hemos visto y oído.', reference: 'Hechos 4,20' },
  { day: 113, verse: 'El Señor me ha enviado a anunciar la Buena Noticia a los pobres.', reference: 'Lucas 4,18' },
  { day: 114, verse: 'Anda, haz tú lo mismo.', reference: 'Lucas 10,37' },
  { day: 115, verse: 'Donde esté vuestro tesoro, allí estará también vuestro corazón.', reference: 'Lucas 12,34' },
  { day: 116, verse: 'Estad preparados, porque el Hijo del hombre vendrá a la hora que menos penséis.', reference: 'Lucas 12,40' },
  { day: 117, verse: 'Dios no es injusto para olvidar vuestro trabajo y el amor que habéis mostrado hacia su nombre.', reference: 'Hebreos 6,10' },
  { day: 118, verse: 'Mantengamos firme la esperanza que profesamos, porque fiel es el que hizo la promesa.', reference: 'Hebreos 10,23' },
  { day: 119, verse: 'Estimulémonos mutuamente en la caridad y en las buenas obras.', reference: 'Hebreos 10,24' },
  { day: 120, verse: 'Corramos con perseverancia la carrera que se nos propone, fijos los ojos en Jesús.', reference: 'Hebreos 12,1-2' },
  { day: 121, verse: 'Dichoso el hombre que soporta la prueba, porque, superada la prueba, recibirá la corona de la vida.', reference: 'Santiago 1,12' },
  { day: 122, verse: 'Tened por sumo gozo cuando os veáis rodeados de pruebas.', reference: 'Santiago 1,2' },
  { day: 123, verse: 'La tribulación produce paciencia; la paciencia, virtud probada; la virtud probada, esperanza.', reference: 'Romanos 5,3-4' },
  { day: 124, verse: 'Dios ama al que da con alegría.', reference: '2 Corintios 9,7' },
  { day: 125, verse: 'No nos cansemos de hacer el bien, porque a su debido tiempo cosecharemos.', reference: 'Gálatas 6,9' },
  { day: 126, verse: 'Estad firmes, inconmovibles, progresando siempre en la obra del Señor.', reference: '1 Corintios 15,58' },
  { day: 127, verse: 'Olvidando lo que queda atrás y lanzándome hacia lo que está por delante, corro hacia la meta.', reference: 'Filipenses 3,13-14' },
  { day: 128, verse: 'Fiel es el que os llama, y Él también lo hará.', reference: '1 Tesalonicenses 5,24' },
  { day: 129, verse: 'No te avergüences del testimonio de nuestro Señor.', reference: '2 Timoteo 1,8' },
  { day: 130, verse: 'El Señor me librará de toda obra mala y me salvará llevándome a su Reino celestial.', reference: '2 Timoteo 4,18' },
  { day: 131, verse: 'He combatido el buen combate, he terminado la carrera, he conservado la fe.', reference: '2 Timoteo 4,7' },
  { day: 132, verse: 'La paciencia os es necesaria para que, después de haber cumplido la voluntad de Dios, alcancéis la promesa.', reference: 'Hebreos 10,36' },
  { day: 133, verse: 'Dad gracias al Señor porque es bueno, porque es eterna su misericordia.', reference: 'Salmo 136,1' },
  { day: 134, verse: 'Este es el día que hizo el Señor, exultemos y alegrémonos en él.', reference: 'Salmo 118,24' },
  { day: 135, verse: 'Cantad al Señor un cántico nuevo, porque ha hecho maravillas.', reference: 'Salmo 98,1' },
  { day: 136, verse: 'El Señor ha estado grande con nosotros, y estamos alegres.', reference: 'Salmo 126,3' },
  { day: 137, verse: 'El gozo del Señor es vuestra fortaleza.', reference: 'Nehemías 8,10' },
  { day: 138, verse: 'Bendice, alma mía, al Señor, y no olvides sus beneficios.', reference: 'Salmo 103,2' },
  { day: 139, verse: 'Gustad y ved qué bueno es el Señor. Dichoso el que se acoge a Él.', reference: 'Salmo 34,9' },
  { day: 140, verse: 'Los que siembran entre lágrimas, cosechan entre cantos.', reference: 'Salmo 126,5' },
  { day: 141, verse: 'Tu amor es mejor que la vida.', reference: 'Salmo 63,4' },
  { day: 142, verse: 'Vuestra tristeza se convertirá en gozo.', reference: 'Juan 16,20' },
  { day: 143, verse: 'Nadie os podrá quitar vuestro gozo.', reference: 'Juan 16,22' },
  { day: 144, verse: 'Alegraos con los que se alegran, llorad con los que lloran.', reference: 'Romanos 12,15' },
  { day: 145, verse: 'El Reino de Dios es justicia, paz y gozo en el Espíritu Santo.', reference: 'Romanos 14,17' },
  { day: 146, verse: 'Estad siempre alegres.', reference: '1 Tesalonicenses 5,16' },
  { day: 147, verse: 'El principio de la sabiduría es el temor del Señor.', reference: 'Proverbios 1,7' },
  { day: 148, verse: 'Confía en el Señor de todo corazón, y Él enderezará tus sendas.', reference: 'Proverbios 3,5-6' },
  { day: 149, verse: 'Sobre todo, guarda tu corazón, porque de él brotan las fuentes de la vida.', reference: 'Proverbios 4,23' },
  { day: 150, verse: 'Te instruiré y te enseñaré el camino que debes seguir; te aconsejaré con mis ojos puestos en ti.', reference: 'Salmo 32,8' },
  { day: 151, verse: 'Tu palabra es lámpara para mis pasos, luz en mi sendero.', reference: 'Salmo 119,105' },
  { day: 152, verse: 'Enséñame a cumplir tu voluntad, porque Tú eres mi Dios.', reference: 'Salmo 143,10' },
  { day: 153, verse: 'El Señor da la sabiduría; de su boca brotan el conocimiento y la inteligencia.', reference: 'Proverbios 2,6' },
  { day: 154, verse: 'La respuesta amable aplaca la ira, la palabra hiriente enciende la cólera.', reference: 'Proverbios 15,1' },
  { day: 155, verse: 'El que habla con sensatez es apreciado.', reference: 'Proverbios 16,21' },
  { day: 156, verse: 'Hay caminos que al hombre le parecen rectos, pero al final son caminos de muerte.', reference: 'Proverbios 14,12' },
  { day: 157, verse: 'Escucha el consejo y acepta la corrección; así serás sabio para el futuro.', reference: 'Proverbios 19,20' },
  { day: 158, verse: 'Instruye al niño en el camino que debe seguir, y ni de viejo se apartará de él.', reference: 'Proverbios 22,6' },
  { day: 159, verse: 'El que perdona la falta busca el amor.', reference: 'Proverbios 17,9' },
  { day: 160, verse: 'El que oculta sus faltas no prospera; el que las confiesa y las abandona alcanza misericordia.', reference: 'Proverbios 28,13' },
  { day: 161, verse: 'Un amigo fiel es un refugio seguro; el que lo encuentra ha encontrado un tesoro.', reference: 'Eclesiástico 6,14' },
  { day: 162, verse: 'Él sana los corazones quebrantados y venda sus heridas.', reference: 'Salmo 147,3' },
  { day: 163, verse: 'Venid a mí todos los que estáis fatigados y agobiados, y yo os aliviaré.', reference: 'Mateo 11,28' },
  { day: 164, verse: 'Ánimo, hija, tu fe te ha salvado.', reference: 'Mateo 9,22' },
  { day: 165, verse: 'En el mundo tendréis tribulación, pero confiad: yo he vencido al mundo.', reference: 'Juan 16,33' },
  { day: 166, verse: 'La paz os dejo, mi paz os doy. No os la doy como la da el mundo.', reference: 'Juan 14,27' },
  { day: 167, verse: 'No se turbe vuestro corazón ni se acobarde.', reference: 'Juan 14,27' },
  { day: 168, verse: 'El Señor sostiene a todos los que caen y endereza a los que están encorvados.', reference: 'Salmo 145,14' },
  { day: 169, verse: 'Él te cubrirá con sus plumas, bajo sus alas encontrarás refugio.', reference: 'Salmo 91,4' },
  { day: 170, verse: 'Cuando pases por las aguas, yo estaré contigo; cuando cruces los ríos, no te ahogarán.', reference: 'Isaías 43,2' },
  { day: 171, verse: 'No temas, porque yo te he rescatado, te he llamado por tu nombre, tú eres mío.', reference: 'Isaías 43,1' },
  { day: 172, verse: 'Consolad, consolad a mi pueblo, dice vuestro Dios.', reference: 'Isaías 40,1' },
  { day: 173, verse: 'Él da fuerza al cansado y acrecienta el vigor del débil.', reference: 'Isaías 40,29' },
  { day: 174, verse: 'Bendito sea el Dios y Padre de nuestro Señor Jesucristo, Padre de las misericordias y Dios de toda consolación.', reference: '2 Corintios 1,3' },
  { day: 175, verse: 'Sabemos que todas las cosas ayudan a bien a los que aman a Dios.', reference: 'Romanos 8,28' },
  { day: 176, verse: 'Antes de formarte en el vientre te conocí, antes de que salieras del seno te consagré.', reference: 'Jeremías 1,5' },
  { day: 177, verse: 'Os daré un corazón nuevo y pondré un espíritu nuevo dentro de vosotros.', reference: 'Ezequiel 36,26' },
  { day: 178, verse: 'Sed fecundos y multiplicaos, llenad la tierra y sometedla.', reference: 'Génesis 1,28' },
  { day: 179, verse: 'Dios vio todo lo que había hecho, y era muy bueno.', reference: 'Génesis 1,31' },
  { day: 180, verse: 'Yo estaré contigo.', reference: 'Éxodo 3,12' },
  { day: 181, verse: 'Yo soy el que soy.', reference: 'Éxodo 3,14' },
  { day: 182, verse: 'Escoge, pues, la vida, para que vivas tú y tu descendencia.', reference: 'Deuteronomio 30,19' },
  { day: 183, verse: 'Sé fuerte y muy valiente. No temas ni te acobardes, porque el Señor tu Dios estará contigo.', reference: 'Josué 1,9' },
  { day: 184, verse: 'Habla, Señor, que tu siervo escucha.', reference: '1 Samuel 3,10' },
  { day: 185, verse: 'El Señor no mira lo que mira el hombre; el hombre mira las apariencias, pero el Señor mira el corazón.', reference: '1 Samuel 16,7' },
  { day: 186, verse: 'Enséñanos a contar nuestros días, para que adquiramos un corazón sabio.', reference: 'Salmo 90,12' },
  { day: 187, verse: 'Qué es el hombre para que te acuerdes de él, el ser humano para que de él te ocupes?', reference: 'Salmo 8,5' },
  { day: 188, verse: 'Lo hiciste poco inferior a los ángeles, lo coronaste de gloria y esplendor.', reference: 'Salmo 8,6' },
  { day: 189, verse: 'Los que confían en el Señor son como el monte Sión: no cae, sino que permanece para siempre.', reference: 'Salmo 125,1' },
  { day: 190, verse: 'El Señor guarda tus entradas y salidas, ahora y para siempre.', reference: 'Salmo 121,8' },
  { day: 191, verse: 'Levanto mis ojos a los montes: ¿de dónde me vendrá el auxilio?', reference: 'Salmo 121,1' },
  { day: 192, verse: 'Mi auxilio viene del Señor, que hizo el cielo y la tierra.', reference: 'Salmo 121,2' },
  { day: 193, verse: 'Id por todo el mundo y proclamad la Buena Noticia a toda la creación.', reference: 'Marcos 16,15' },
  { day: 194, verse: 'Vosotros sois testigos de esto.', reference: 'Lucas 24,48' },
  { day: 195, verse: 'Recibiréis la fuerza del Espíritu Santo, que vendrá sobre vosotros, y seréis mis testigos.', reference: 'Hechos 1,8' },
  { day: 196, verse: 'Os anunciamos lo que hemos visto y oído, para que también vosotros tengáis comunión con nosotros.', reference: '1 Juan 1,3' },
  { day: 197, verse: 'Dad razón de vuestra esperanza a todo el que os pida explicación.', reference: '1 Pedro 3,15' },
  { day: 198, verse: 'Sed modelos para los creyentes en palabra, conducta, amor, fe y pureza.', reference: '1 Timoteo 4,12' },
  { day: 199, verse: 'Los sabios brillarán como el resplandor del firmamento.', reference: 'Daniel 12,3' },
  { day: 200, verse: 'Cuenta las maravillas de Dios entre las naciones.', reference: '1 Crónicas 16,24' },
  { day: 201, verse: 'Grande es el Señor y muy digno de alabanza.', reference: 'Salmo 145,3' },
  { day: 202, verse: 'Una generación alabará tus obras a la otra y anunciará tus hazañas.', reference: 'Salmo 145,4' },
  { day: 203, verse: 'Todo lo que respira alabe al Señor.', reference: 'Salmo 150,6' },
  { day: 204, verse: 'Cantad al Señor un cántico nuevo, resuene su alabanza en la asamblea de los fieles.', reference: 'Salmo 149,1' },
  { day: 205, verse: 'El que da testimonio verdadero salva vidas.', reference: 'Proverbios 14,25' },
  { day: 206, verse: 'El pueblo que caminaba en tinieblas vio una gran luz.', reference: 'Isaías 9,1' },
  { day: 207, verse: 'Porque nos ha nacido un niño, un hijo se nos ha dado.', reference: 'Isaías 9,5' },
  { day: 208, verse: 'Su nombre será: Consejero admirable, Dios fuerte, Padre eterno, Príncipe de la paz.', reference: 'Isaías 9,5' },
  { day: 209, verse: 'He aquí que la virgen concebirá y dará a luz un hijo, y le pondrá por nombre Emmanuel.', reference: 'Isaías 7,14' },
  { day: 210, verse: 'Gloria a Dios en las alturas y en la tierra paz a los hombres de buena voluntad.', reference: 'Lucas 2,14' },
  { day: 211, verse: 'Os ha nacido hoy, en la ciudad de David, un Salvador: el Mesías, el Señor.', reference: 'Lucas 2,11' },
  { day: 212, verse: 'María, por su parte, guardaba todas estas cosas y las meditaba en su corazón.', reference: 'Lucas 2,19' },
  { day: 213, verse: 'Y la Palabra se hizo carne y habitó entre nosotros.', reference: 'Juan 1,14' },
  { day: 214, verse: 'En él estaba la vida, y la vida era la luz de los hombres.', reference: 'Juan 1,4' },
  { day: 215, verse: 'La luz brilla en las tinieblas, y las tinieblas no la vencieron.', reference: 'Juan 1,5' },
  { day: 216, verse: 'La Palabra era la luz verdadera que ilumina a todo hombre.', reference: 'Juan 1,9' },
  { day: 217, verse: 'Mientras tenéis la luz, creed en la luz, para que seáis hijos de la luz.', reference: 'Juan 12,36' },
  { day: 218, verse: 'Velad, pues, porque no sabéis qué día vendrá vuestro Señor.', reference: 'Mateo 24,42' },
  { day: 219, verse: 'Bien, siervo bueno y fiel; has sido fiel en lo poco, te pondré al frente de lo mucho.', reference: 'Mateo 25,21' },
  { day: 220, verse: 'Venid, benditos de mi Padre, recibid en herencia el Reino preparado para vosotros.', reference: 'Mateo 25,34' },
  { day: 221, verse: 'En verdad os digo: cuanto hicisteis a uno de estos hermanos míos más pequeños, a mí me lo hicisteis.', reference: 'Mateo 25,40' },
  { day: 222, verse: 'El que quiera ser grande entre vosotros, que sea vuestro servidor.', reference: 'Mateo 20,26' },
  { day: 223, verse: 'El Reino de Dios ya está entre vosotros.', reference: 'Lucas 17,21' },
  { day: 224, verse: 'Yo soy el Alfa y la Omega, el Primero y el Último, el Principio y el Fin.', reference: 'Apocalipsis 22,13' },
  { day: 225, verse: 'El que da testimonio de estas cosas dice: ’Sí, vengo pronto’. Amén. ¡Ven, Señor Jesús!', reference: 'Apocalipsis 22,20' },
  { day: 226, verse: 'Vi un cielo nuevo y una tierra nueva.', reference: 'Apocalipsis 21,1' },
  { day: 227, verse: 'Dios enjugará toda lágrima de sus ojos. Ya no habrá muerte, ni luto, ni llanto, ni dolor.', reference: 'Apocalipsis 21,4' },
  { day: 228, verse: 'El que tenga sed, que se acerque; el que quiera, que reciba gratuitamente el agua de la vida.', reference: 'Apocalipsis 22,17' },
  { day: 229, verse: 'La gracia del Señor Jesús esté con todos. Amén.', reference: 'Apocalipsis 22,21' },
  { day: 230, verse: 'Dichoso el que teme al Señor y sigue sus caminos.', reference: 'Salmo 128,1' },
  { day: 231, verse: 'El Señor es mi roca, mi fortaleza y mi libertador.', reference: 'Salmo 18,3' },
  { day: 232, verse: 'Los cielos proclaman la gloria de Dios, el firmamento anuncia la obra de sus manos.', reference: 'Salmo 19,2' },
  { day: 233, verse: 'La ley del Señor es perfecta, refrigerio del alma.', reference: 'Salmo 19,8' },
  { day: 234, verse: 'Del Señor es la tierra y cuanto la llena, el orbe y todos sus habitantes.', reference: 'Salmo 24,1' },
  { day: 235, verse: 'Muéstrame, Señor, tus caminos, enséñame tus sendas.', reference: 'Salmo 25,4' },
  { day: 236, verse: 'El Señor es bueno y recto, por eso enseña el camino a los pecadores.', reference: 'Salmo 25,8' },
  { day: 237, verse: 'Los pasos del hombre los dirige el Señor; ¿cómo puede el hombre comprender su camino?', reference: 'Proverbios 20,24' },
  { day: 238, verse: 'La misericordia y la verdad se encuentran, la justicia y la paz se besan.', reference: 'Salmo 85,11' },
  { day: 239, verse: 'Sed fuertes y animosos, no temáis ni os asustéis ante ellos.', reference: 'Deuteronomio 31,6' },
  { day: 240, verse: 'El Señor, tu Dios, es quien va contigo; no te dejará ni te abandonará.', reference: 'Deuteronomio 31,6' },
  { day: 241, verse: 'El Señor es mi fortaleza y mi canto, Él es mi salvación.', reference: 'Salmo 118,14' },
  { day: 242, verse: 'Te doy gracias porque me has escuchado, y has sido mi salvación.', reference: 'Salmo 118,21' },
  { day: 243, verse: 'La piedra que desecharon los constructores, en piedra angular se ha convertido.', reference: 'Salmo 118,22' },
  { day: 244, verse: 'Bendito el que viene en nombre del Señor.', reference: 'Salmo 118,26' },
  { day: 245, verse: 'Tú eres mi Dios, te doy gracias; Dios mío, te exalto.', reference: 'Salmo 118,28' },
  { day: 246, verse: 'Feliz el que teme al Señor y camina por sus caminos.', reference: 'Salmo 128,1' },
  { day: 247, verse: 'Desde Sión te bendiga el Señor: que veas la dicha de Jerusalén.', reference: 'Salmo 128,5' },
  { day: 248, verse: 'Señor, tú has sido nuestro refugio de generación en generación.', reference: 'Salmo 90,1' },
  { day: 249, verse: 'Mil años son ante tus ojos como el día de ayer, que pasó.', reference: 'Salmo 90,4' },
  { day: 250, verse: 'Sácianos de tu misericordia por la mañana, y daremos gritos de júbilo.', reference: 'Salmo 90,14' },
  { day: 251, verse: 'Los ojos del Señor están sobre los que le temen, sobre los que esperan en su misericordia.', reference: 'Salmo 33,18' },
  { day: 252, verse: 'Muchas son las desgracias del justo, pero de todas le salva el Señor.', reference: 'Salmo 34,20' },
  { day: 253, verse: 'Los justos claman, el Señor los escucha y los libra de todas sus angustias.', reference: 'Salmo 34,18' },
  { day: 254, verse: 'Guarda mi alma, porque soy tuyo; salva a tu siervo que confía en ti.', reference: 'Salmo 86,2' },
  { day: 255, verse: 'Tú, Señor, eres bueno y perdonador, rico en misericordia con los que te invocan.', reference: 'Salmo 86,5' },
  { day: 256, verse: 'Tú, Señor, eres un Dios clemente y misericordioso, lento a la ira y rico en amor y verdad.', reference: 'Salmo 86,15' },
  { day: 257, verse: 'El que habita al abrigo del Altísimo, mora a la sombra del Omnipotente.', reference: 'Salmo 91,1' },
  { day: 258, verse: 'Ningún mal te sobrevendrá, ninguna plaga llegará a tu tienda.', reference: 'Salmo 91,10' },
  { day: 259, verse: 'Puesto que me ama, yo lo libraré; lo protegeré, porque conoce mi nombre.', reference: 'Salmo 91,14' },
  { day: 260, verse: 'Cuando me invoque, le responderé; estaré con él en la angustia.', reference: 'Salmo 91,15' },
  { day: 261, verse: 'Él es nuestro Dios, y nosotros el pueblo de su dehesa, el rebaño de su mano.', reference: 'Salmo 95,7' },
  { day: 262, verse: 'El Señor reina, la tierra goza, se alegran las islas innumerables.', reference: 'Salmo 97,1' },
  { day: 263, verse: 'El Señor ama al que odia el mal, protege la vida de sus fieles.', reference: 'Salmo 97,10' },
  { day: 264, verse: 'Luz amanece para el justo, y alegría para los rectos de corazón.', reference: 'Salmo 97,11' },
  { day: 265, verse: 'El Señor viene a gobernar la tierra: gobernará el orbe con justicia.', reference: 'Salmo 98,9' },
  { day: 266, verse: 'Servid al Señor con alegría, llegad hasta Él con cantos de júbilo.', reference: 'Salmo 100,2' },
  { day: 267, verse: 'Entrad por sus puertas con acción de gracias, por sus atrios con himnos.', reference: 'Salmo 100,4' },
  { day: 268, verse: 'Porque el Señor es bueno, su misericordia es eterna, su fidelidad de generación en generación.', reference: 'Salmo 100,5' },
  { day: 269, verse: 'Bendice, alma mía, al Señor, y todo mi ser a su santo nombre.', reference: 'Salmo 103,1' },
  { day: 270, verse: 'Él perdona todas tus culpas, cura todas tus dolencias.', reference: 'Salmo 103,3' },
  { day: 271, verse: 'Él rescata tu vida de la fosa, te corona de amor y de ternura.', reference: 'Salmo 103,4' },
  { day: 272, verse: 'El Señor es compasivo y misericordioso, lento a la ira y rico en amor.', reference: 'Salmo 103,8' },
  { day: 273, verse: 'No nos trata según nuestros pecados, ni nos paga según nuestras culpas.', reference: 'Salmo 103,10' },
  { day: 274, verse: 'Como un padre siente ternura por sus hijos, así el Señor siente ternura por los que le temen.', reference: 'Salmo 103,13' },
  { day: 275, verse: 'La misericordia del Señor desde siempre hasta siempre sobre los que le temen.', reference: 'Salmo 103,17' },
  { day: 276, verse: 'Te alabaré, Señor, de todo corazón, daré a conocer todas tus maravillas.', reference: 'Salmo 9,2' },
  { day: 277, verse: 'El Señor es refugio del oprimido, baluarte en los momentos de angustia.', reference: 'Salmo 9,10' },
  { day: 278, verse: 'Confían en ti los que conocen tu nombre, porque no abandonas a los que te buscan.', reference: 'Salmo 9,11' },
  { day: 279, verse: 'Vuelve, Señor, ¿hasta cuándo? Ten compasión de tus siervos.', reference: 'Salmo 90,13' },
  { day: 280, verse: 'Que la bondad del Señor, nuestro Dios, descanse sobre nosotros.', reference: 'Salmo 90,17' },
  { day: 281, verse: 'Afianza, Señor, la obra de nuestras manos.', reference: 'Salmo 90,17' },
  { day: 282, verse: 'La bondad de un hombre le hace apreciable.', reference: 'Proverbios 19,22' },
  { day: 283, verse: 'El Señor da la muerte y la vida, da la pobreza y la riqueza.', reference: '1 Samuel 2,7' },
  { day: 284, verse: 'Conmigo puedes derrotar a un ejército, con mi Dios puedo saltar una muralla.', reference: 'Salmo 18,30' },
  { day: 285, verse: 'Tú eres mi Dios, en tus manos está mi destino.', reference: 'Salmo 31,15-16' },
  { day: 286, verse: 'No temerás los terrores de la noche, ni la flecha que vuela de día.', reference: 'Salmo 91,5' },
  { day: 287, verse: 'Los ángeles te llevarán en sus manos, para que tu pie no tropiece en la piedra.', reference: 'Salmo 91,12' },
  { day: 288, verse: 'Aunque caigan mil a tu lado y diez mil a tu derecha, a ti no te alcanzará.', reference: 'Salmo 91,7' },
  { day: 289, verse: 'El Señor te guarda de todo mal, Él guarda tu alma.', reference: 'Salmo 121,7' },
  { day: 290, verse: 'Sácianos de tu amor por la mañana, y cantaremos alegres toda la vida.', reference: 'Salmo 90,14' },
  { day: 291, verse: 'Bienaventurado el que cuida del pobre y del desvalido; en el día de la desgracia lo salvará el Señor.', reference: 'Salmo 41,2' },
  { day: 292, verse: 'El Señor guarda a los sencillos: estando sin fuerzas, me salvó.', reference: 'Salmo 116,6' },
  { day: 293, verse: 'Los cielos pregonan su justicia, todos los pueblos contemplan su gloria.', reference: 'Salmo 97,6' },
  { day: 294, verse: 'Con trompetas y al son de cuernos, aclamad al Rey, el Señor.', reference: 'Salmo 98,6' },
  { day: 295, verse: 'El Señor no mira lo que mira el hombre; mira el corazón.', reference: '1 Samuel 16,7' },
  { day: 296, verse: 'El temor del Señor es escuela de sabiduría.', reference: 'Proverbios 15,33' },
  { day: 297, verse: 'Bienaventurados los que trabajan por la paz, porque serán llamados hijos de Dios.', reference: 'Mateo 5,9' },
  { day: 298, verse: 'Cada uno ha recibido su gracia según la medida del don de Cristo.', reference: 'Efesios 4,7' },
  { day: 299, verse: 'El que se pone a la defensa del pobre es como Jesús.', reference: 'Proverbios 19,17' },
  { day: 300, verse: 'Dios no es de confusión, sino de paz.', reference: '1 Corintios 14,33' },
  { day: 301, verse: 'La senda del justo es recta; Tú allanas la ruta del justo.', reference: 'Isaías 26,7' },
  { day: 302, verse: 'Dichoso el hombre que soporta la prueba, porque recibirá la corona de la vida.', reference: 'Santiago 1,12' },
  { day: 303, verse: 'El que siembra con lágrimas cosecha con cantos.', reference: 'Salmo 126,5' },
  { day: 304, verse: 'El Señor te bendiga y te guarde, ilumine su rostro sobre ti y te conceda su paz.', reference: 'Números 6,24-26' },
  { day: 305, verse: 'Caña quebrada no quebrará, mecha vacilante no apagará.', reference: 'Isaías 42,3' },
  { day: 306, verse: 'El Señor os dará pan en la angustia y agua en la aflicción.', reference: 'Isaías 30,20' },
  { day: 307, verse: 'El que habita al abrigo del Altísimo, mora a la sombra del Omnipotente.', reference: 'Salmo 91,1' },
  { day: 308, verse: 'Dios es nuestro refugio y nuestra fuerza, auxilio siempre a punto en la angustia.', reference: 'Salmo 46,2' },
  { day: 309, verse: 'El Señor está cerca de los que le invocan, de los que le invocan sinceramente.', reference: 'Salmo 145,18' },
  { day: 310, verse: 'El Señor da la sabiduría; de su boca brotan el conocimiento y la inteligencia.', reference: 'Proverbios 2,6' },
  { day: 311, verse: 'El corazón inteligente busca el conocimiento.', reference: 'Proverbios 15,14' },
  { day: 312, verse: 'Más vale paciencia que arrogancia.', reference: 'Eclesiastés 7,8' },
  { day: 313, verse: 'El Señor está conmigo, no temo; ¿qué puede hacerme el hombre?', reference: 'Salmo 118,6' },
  { day: 314, verse: 'Más vale refugiarse en el Señor que confiar en el hombre.', reference: 'Salmo 118,8' },
  { day: 315, verse: 'Más vale refugiarse en el Señor que confiar en los príncipes.', reference: 'Salmo 118,9' },
  { day: 316, verse: 'Abridme las puertas de la justicia, para entrar a dar gracias al Señor.', reference: 'Salmo 118,19' },
  { day: 317, verse: 'El Señor es Dios, Él nos ilumina.', reference: 'Salmo 118,27' },
  { day: 318, verse: 'He aquí la bendición del Señor para los que le temen.', reference: 'Salmo 128,4' },
  { day: 319, verse: 'Alabad a Dios en su santuario, alabadlo en su poderoso firmamento.', reference: 'Salmo 150,1' },
  { day: 320, verse: 'El Señor es bueno con todos, es cariñoso con todas sus criaturas.', reference: 'Salmo 145,9' },
  { day: 321, verse: 'El Señor sostiene a todos los que caen y endereza a los que están encorvados.', reference: 'Salmo 145,14' },
  { day: 322, verse: 'El Señor guarda a todos los que le aman.', reference: 'Salmo 145,20' },
  { day: 323, verse: 'Cantad alegres al Señor, porque viene a gobernar la tierra.', reference: 'Salmo 96,12' },
  { day: 324, verse: 'La gloria de los jóvenes es su fuerza, el honor de los viejos son sus canas.', reference: 'Proverbios 20,29' },
  { day: 325, verse: 'El Señor está cerca de los que le invocan sinceramente.', reference: 'Salmo 145,18' },
  { day: 326, verse: 'Clama a mí y te responderé, y te anunciaré cosas grandes y escondidas.', reference: 'Jeremías 33,3' },
  { day: 327, verse: 'El Señor es mi parte, dice mi alma; por eso espero en él.', reference: 'Lamentaciones 3,24' },
  { day: 328, verse: 'Bueno es el Señor para los que en él esperan, para el alma que le busca.', reference: 'Lamentaciones 3,25' },
  { day: 329, verse: 'La misericordia del Señor no se acaba, no se han agotado sus ternuras.', reference: 'Lamentaciones 3,22' },
  { day: 330, verse: 'Algo nuevo está brotando, ¿no lo notas?', reference: 'Isaías 43,19' },
  { day: 331, verse: 'Paz, paz al lejano y al cercano, dice el Señor.', reference: 'Isaías 57,19' },
  { day: 332, verse: 'El Señor te guiará siempre, saciará tu alma en los sequedales.', reference: 'Isaías 58,11' },
  { day: 333, verse: 'Te desposaré conmigo para siempre, te desposaré en justicia y en derecho.', reference: 'Oseas 2,21' },
  { day: 334, verse: 'El Señor tu Dios está en medio de ti, poderoso salvador.', reference: 'Sofonías 3,17' },
  { day: 335, verse: 'Buscad al Señor mientras se deja encontrar, llamadle mientras está cerca.', reference: 'Isaías 55,6' },
  { day: 336, verse: 'Mi palabra no volverá a mí vacía, sino que hará mi voluntad.', reference: 'Isaías 55,11' },
  { day: 337, verse: 'Convertíos a mí y os salvaré.', reference: 'Isaías 45,22' },
  { day: 338, verse: 'El Señor es mi luz y mi salvación, ¿a quién temeré?', reference: 'Salmo 27,1' },
  { day: 339, verse: 'Espera en el Señor, ten valor y firmeza, espera en el Señor.', reference: 'Salmo 27,14' },
  { day: 340, verse: 'El Señor da fuerza a su pueblo, el Señor bendice a su pueblo con la paz.', reference: 'Salmo 29,11' },
  { day: 341, verse: 'A ti, Señor, elevo mi alma.', reference: 'Salmo 25,1' },
  { day: 342, verse: 'En ti confío, Dios mío, no quede yo defraudado.', reference: 'Salmo 25,2' },
  { day: 343, verse: 'Guíame en tu verdad, enséñame, porque tú eres el Dios de mi salvación.', reference: 'Salmo 25,5' },
  { day: 344, verse: 'Acuérdate, Señor, de tu ternura y de tu amor, que son de siempre.', reference: 'Salmo 25,6' },
  { day: 345, verse: 'Perdona, Señor, mis culpas, que son muchas.', reference: 'Salmo 25,11' },
  { day: 346, verse: 'El Señor hace justicia y derecho a todos los oprimidos.', reference: 'Salmo 103,6' },
  { day: 347, verse: 'El Señor conoce nuestros pensamientos, sabe que somos polvo.', reference: 'Salmo 103,14' },
  { day: 348, verse: 'El amor del Señor es eterno para los que le temen.', reference: 'Salmo 103,17' },
  { day: 349, verse: 'Bendecid al Señor, todas sus obras, en todos los lugares de su imperio.', reference: 'Salmo 103,22' },
  { day: 350, verse: 'Dad gracias al Señor porque es bueno, porque es eterna su misericordia.', reference: 'Salmo 118,1' },
  { day: 351, verse: 'Diga la casa de Israel: eterna es su misericordia.', reference: 'Salmo 118,2' },
  { day: 352, verse: 'Digan los que temen al Señor: eterna es su misericordia.', reference: 'Salmo 118,4' },
  { day: 353, verse: 'El Señor es mi fortaleza y mi canto, él es mi salvación.', reference: 'Salmo 118,14' },
  { day: 354, verse: 'El Señor me ha escuchado, él es mi salvación.', reference: 'Salmo 118,21' },
  { day: 355, verse: 'Es el Señor quien ha hecho esto, admirable a nuestros ojos.', reference: 'Salmo 118,23' },
  { day: 356, verse: 'Alégrate y regocíjate, porque el Señor hizo maravillas.', reference: 'Joel 2,21' },
  { day: 357, verse: 'El Señor tu Dios está contigo, él salva con su amor.', reference: 'Sofonías 3,17' },
  { day: 358, verse: 'Dichosos los que tienen hambre y sed de justicia, porque serán saciados.', reference: 'Mateo 5,6' },
  { day: 359, verse: 'Bienaventurados los perseguidos por causa de la justicia, porque de ellos es el Reino de los Cielos.', reference: 'Mateo 5,10' },
  { day: 360, verse: 'Vosotros sois mis amigos si hacéis lo que yo os mando.', reference: 'Juan 15,14' },
  { day: 361, verse: 'No sois vosotros los que me habéis elegido, soy yo quien os he elegido.', reference: 'Juan 15,16' },
  { day: 362, verse: 'En el amor no hay temor, sino que el amor perfecto echa fuera el temor.', reference: '1 Juan 4,18' },
  { day: 363, verse: 'Dios es luz, en él no hay tiniebla alguna.', reference: '1 Juan 1,5' },
  { day: 364, verse: 'Si caminamos en la luz, como él está en la luz, estamos en comunión unos con otros.', reference: '1 Juan 1,7' },
  { day: 365, verse: 'El que dice que está en la luz y odia a su hermano, está todavía en las tinieblas.', reference: '1 Juan 2,9' },
  { day: 366, verse: 'No améis al mundo ni lo que hay en él. El mundo pasa, pero el que hace la voluntad de Dios permanece para siempre.', reference: '1 Juan 2,15-17' },
  { day: 367, verse: 'Mirad qué amor nos ha tenido el Padre para llamarnos hijos de Dios.', reference: '1 Juan 3,1' },
  { day: 368, verse: 'En esto conocemos lo que es el amor: en que él dio su vida por nosotros.', reference: '1 Juan 3,16' },
  { day: 369, verse: 'El que permanece en el amor permanece en Dios, y Dios en él.', reference: '1 Juan 4,16' },
  { day: 370, verse: 'No amemos de palabra ni de lengua, sino de verdad y con obras.', reference: '1 Juan 3,18' },
  { day: 371, verse: 'Por el amor que os tengáis los unos a los otros reconocerán todos que sois discípulos míos.', reference: 'Juan 13,35' },
  { day: 372, verse: 'Felices los que escuchan la palabra de Dios y la cumplen.', reference: 'Lucas 11,28' },
  { day: 373, verse: 'Todo el que hace la verdad va a la luz.', reference: 'Juan 3,21' },
  { day: 374, verse: 'El que acepta su testimonio certifica que Dios es veraz.', reference: 'Juan 3,33' },
  { day: 375, verse: 'El que viene del cielo está por encima de todos.', reference: 'Juan 3,31' },
  { day: 376, verse: 'Dios es espíritu, y los que le adoran deben adorarle en espíritu y verdad.', reference: 'Juan 4,24' },
  { day: 377, verse: 'Mi alimento es hacer la voluntad del que me ha enviado y llevar a cabo su obra.', reference: 'Juan 4,34' },
  { day: 378, verse: 'Levantad los ojos y mirad los campos, que ya están dorados para la mies.', reference: 'Juan 4,35' },
  { day: 379, verse: 'El que siega recibe su salario y recoge fruto para la vida eterna.', reference: 'Juan 4,36' },
  { day: 380, verse: 'La Escritura no puede ser quebrantada.', reference: 'Juan 10,35' },
  { day: 381, verse: 'Yo soy el buen pastor. El buen pastor da su vida por las ovejas.', reference: 'Juan 10,11' },
  { day: 382, verse: 'Yo conozco a mis ovejas y ellas me conocen a mí.', reference: 'Juan 10,14' },
  { day: 383, verse: 'Tengo otras ovejas que no son de este redil; también a esas tengo que traer.', reference: 'Juan 10,16' },
  { day: 384, verse: 'Nadie me quita la vida, yo la doy voluntariamente.', reference: 'Juan 10,18' },
  { day: 385, verse: 'Yo soy la resurrección y la vida; el que cree en mí, aunque muera, vivirá.', reference: 'Juan 11,25' },
  { day: 386, verse: 'El que cree en mí no cree solo en mí, sino en el que me ha enviado.', reference: 'Juan 12,44' },
  { day: 387, verse: 'Yo, la luz, he venido al mundo para que todo el que crea en mí no siga en tinieblas.', reference: 'Juan 12,46' },
  { day: 388, verse: 'Si yo, el Señor y el Maestro, os he lavado los pies, vosotros también debéis lavaros los pies unos a otros.', reference: 'Juan 13,14' },
  { day: 389, verse: 'En esto conocerán que sois discípulos míos: en el amor que os tengáis unos a otros.', reference: 'Juan 13,35' },
  { day: 390, verse: 'No se turbe vuestro corazón. Creéis en Dios, creed también en mí.', reference: 'Juan 14,1' },
  { day: 391, verse: 'En la casa de mi Padre hay muchas moradas; si no, os lo habría dicho.', reference: 'Juan 14,2' },
  { day: 392, verse: 'Yo soy el camino, la verdad y la vida. Nadie va al Padre sino por mí.', reference: 'Juan 14,6' },
  { day: 393, verse: 'Si me conocierais a mí, conoceríais también a mi Padre.', reference: 'Juan 14,7' },
  { day: 394, verse: 'El que me ha visto a mí ha visto al Padre.', reference: 'Juan 14,9' },
  { day: 395, verse: 'Yo ruego por ellos; no ruego por el mundo, sino por los que tú me has dado.', reference: 'Juan 17,9' },
  { day: 396, verse: 'Que todos sean uno, como tú, Padre, estás en mí y yo en ti.', reference: 'Juan 17,21' },
  { day: 397, verse: 'Padre, quiero que donde yo esté, estén también conmigo los que me has dado.', reference: 'Juan 17,24' },
  { day: 398, verse: 'La verdad os hará libres.', reference: 'Juan 8,32' },
  { day: 399, verse: 'El que es de Dios escucha las palabras de Dios.', reference: 'Juan 8,47' },
  { day: 400, verse: 'Yo he venido para que tengan vida y la tengan en abundancia.', reference: 'Juan 10,10' },
  { day: 401, verse: 'El buen pastor da la vida por las ovejas.', reference: 'Juan 10,11' },
];

export function getVerseOfDay(): { verse: string; reference: string } {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const oneDay = 86400000;
  const dayOfYear = Math.floor(diff / oneDay);
  const v = verses.find(v => v.day === dayOfYear) || verses[0];
  return { verse: v.verse, reference: v.reference };
}